### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by AshPowell** [Torann/laravel-asana#17]
Few pull requests pending and I'm tempted to add Laravel 6 support...

**Comment by ClaraLeigh** [comment]
Not sure if its still maintained.... @Torann ? 
I forked it to allow laravel 6 already and just pointed to my fork instead, never did a pull request b/c I thought the project was dead.
See: https://github.com/JeraNS/laravel-asana/commit/9fda8aefcb6abb82dfb50254b5e7e97c97856596

Haven't noticed any bugs, just the bump in compatibility. Would probably change it to allow older laravel and future ones but I was rushed at the time.

**Comment by AshPowell** [comment]
> Not sure if its still maintained.... @Torann ?
> I forked it to allow laravel 6 already and just pointed to my fork instead, never did a pull request b/c I thought the project was dead.
> See: [JeraNS@9fda8ae](https://github.com/JeraNS/laravel-asana/commit/9fda8aefcb6abb82dfb50254b5e7e97c97856596)
> 
> Haven't noticed any bugs, just the bump in compatibility. Would probably change it to allow older laravel and future ones but I was rushed at the time.

Check out this one mate already has a bunch of improvements & on packagist.
https://github.com/ChrisThompsonTLDR/laravel-asana
