### ISSUE TITLE
Cant getting tasks of a specific user

### ISSUE THREAD

**Issue by jishadp** [Torann/laravel-asana#2]
Hi Torann,

I cant see the method for getting all tasks of a specific user, 

I there any function in this package..?

If Yes, please tell me that .

Thanks & Regards

**Comment by Torann** [comment]
There isn't. Let me dig through their API docs and see if I can add it :-)

**Comment by Torann** [comment]
Ok, you should be all set. Checkout [Filtering](https://github.com/Torann/laravel-asana#filtering) in the README.
